### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by r1bnc** [mk-pmb/minetest-csm-rc210117_pmb#1]

**Comment by mk-pmb** [comment]
Hi! The lack of useful docunentation is a known bug, stated in the Readme. How may I help you?

**Comment by mk-pmb** [comment]
It probably doesn't really help you, but I updated the readme to adjust potential optimistic expectations. ;-)

**Comment by r1bnc** [comment]
Oof lol I posted at the wrong repo lol. 

This project is interesting. :D

**Comment by mk-pmb** [comment]
> Oof lol I posted at the wrong repo lol.

Closing as off-topic then.

> This project is interesting. :D

Thanks!
